9AB6BA       7D        51   57AC1709  36    85      3AE764     B6    9E               
90   4F2      D4     A3       D0      05    25     3E     6D   A46   C5                  
5A   6B5       D2   63        DD      5B    D5    33       6D  1DC8  5A                    
9EF61F          D7D8          B1      EF78343D   39        7A  4D 3E 8A               
4D               24           D8      17    E2   6B        0D  2E  5C73                      
54               60           2F      A0    BE    6E      67   1C   62B                     
A3               38           2A      42    D1      40BB01     82    FD